# Generated by Django 6.1.1 on 2026-09-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinprice',
            options={'verbose_name': 'Крипто-монета', 'verbose_name_plural': 'Крипто-монеты'},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Снимок рынка', 'verbose_name_plural': 'Снимки рынка'},
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='coin_id',
            field=models.CharField(max_length=100, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='market_cap',
            field=models.FloatField(verbose_name='Рынчная стоимость'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='price_change_percentage_24h',
            field=models.FloatField(verbose_name='Изменение за 24 часа'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_prices', to='crypto.snapshot', verbose_name='Снимок'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='symbol',
            field=models.CharField(max_length=100, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='total_volume',
            field=models.FloatField(verbose_name='Обьем средств'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_symbol', models.CharField(max_length=50, verbose_name='Монета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Монета в watchlist',
                'verbose_name_plural': 'Монеты в watchlist',
                'ordering': ['coin_symbol'],
                'constraints': [models.UniqueConstraint(fields=('user', 'coin_symbol'), name='unique_user_coin_symbol')],
            },
        ),
    ]
