# Generated by Django 6.1.1 on 2026-09-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_cleanup_orphan_coinprices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinprice',
            options={'verbose_name': 'Крипто-монета', 'verbose_name_plural': 'Крипто-монеты'},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'verbose_name': 'Снимок рынка', 'verbose_name_plural': 'Снимки рынка'},
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='coin_id',
            field=models.CharField(max_length=100, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='market_cap',
            field=models.FloatField(verbose_name='Рынчная стоимость'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='price_change_percentage_24h',
            field=models.FloatField(verbose_name='Изменение за 24 часа'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='snapshot',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='coin_prices', to='crypto.snapshot', verbose_name='Снимок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='symbol',
            field=models.CharField(max_length=100, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='total_volume',
            field=models.FloatField(verbose_name='Обьем средств'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник'),
        ),
    ]
