# Generated by Django 6.1.1 on 2026-09-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_coinprice_options_alter_snapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'ordering': ['coin_symbol'], 'verbose_name': 'Coin hystory', 'verbose_name_plural': 'Монеты отслеживания'},
        ),
    ]
