# Generated by Django 6.1.1 on 2026-09-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_coinprice_options_alter_snapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprice',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Рыночная стоимость'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='price_change_percentage_24h',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Изменение за 24 часа'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='total_volume',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Объём средств'),
        ),
    ]
