# Generated by Django 6.1.1 on 2026-09-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_coinprice_market_cap_alter_coinprice_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Источник'),
        ),
    ]
