# Generated by Django 6.1.1 on 2026-09-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_alter_snapshot_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Снимок рынка', 'verbose_name_plural': 'Снимки рынка'},
        ),
    ]
