# Generated by Django 6.1.1 on 2026-09-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_watchlistitem_options'),
        ('crypto', '0005_alter_snapshot_options'),
    ]

    operations = [
    ]
